# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""OPTEE Syscalls types."""

import enum


class OpteeSysCall(enum.IntEnum):
  """Syscall numbers to OPTEE TEE."""
  RETURN = 0
  LOG = 1
  PANIC = 2
  GET_PROPERTY = 3
  GET_PROPERTY_NAME_TO_INDEX = 4
  OPEN_TA_SESSION = 5
  CLOSE_TA_SESSION = 6
  INVOKE_TA_COMMAND = 7
  CHECK_ACCESS_RIGHTS = 8
  GET_CANCELLATION_FLAG = 9
  UNMASK_CANCELLATION = 10
  MASK_CANCELLATION = 11
  WAIT = 12
  GET_TIME = 13
  SET_TA_TIME = 14
  CRYP_STATE_ALLOC = 15
  CRYP_STATE_COPY = 16
  CRYP_STATE_FREE = 17
  HASH_INIT = 18
  HASH_UPDATE = 19
  HASH_FINAL = 20
  CIPHER_INIT = 21
  CIPHER_UPDATE = 22
  CIPHER_FINAL = 23
  CRYP_OBJ_GET_INFO = 24
  CRYP_OBJ_RESTRICT_USAGE = 25
  CRYP_OBJ_GET_ATTR = 26
  CRYP_OBJ_ALLOC = 27
  CRYP_OBJ_CLOSE = 28
  CRYP_OBJ_RESET = 29
  CRYP_OBJ_POPULATE = 30
  CRYP_OBJ_COPY = 31
  CRYP_DERIVE_KEY = 32
  CRYP_RANDOM_NUMBER_GENERATE = 33
  AUTHENC_INIT = 34
  AUTHENC_UPDATE_AAD = 35
  AUTHENC_UPDATE_PAYLOAD = 36
  AUTHENC_ENC_FINAL = 37
  AUTHENC_DEC_FINAL = 38
  ASYMM_OPERATE = 39
  ASYMM_VERIFY = 40
  STORAGE_OBJ_OPEN = 41
  STORAGE_OBJ_CREATE = 42
  STORAGE_OBJ_DEL = 43
  STORAGE_OBJ_RENAME = 44
  STORAGE_ENUM_ALLOC = 45
  STORAGE_ENUM_FREE = 46
  STORAGE_ENUM_RESET = 47
  STORAGE_ENUM_START = 48
  STORAGE_ENUM_NEXT = 49
  STORAGE_OBJ_READ = 50
  STORAGE_OBJ_WRITE = 51
  STORAGE_OBJ_TRUNC = 52
  STORAGE_OBJ_SEEK = 53
  CRYP_OBJ_GENERATE_KEY = 54
  # Deprecated Secure Element API syscalls return TEE_ERROR_NOT_SUPPORTED
  SE_SERVICE_OPEN__DEPRECATED = 55
  SE_SERVICE_CLOSE__DEPRECATED = 56
  SE_SERVICE_GET_READERS__DEPRECATED = 57
  SE_READER_GET_PROP__DEPRECATED = 58
  SE_READER_GET_NAME__DEPRECATED = 59
  SE_READER_OPEN_SESSION__DEPRECATED = 60
  SE_READER_CLOSE_SESSIONS__DEPRECATED = 61
  SE_SESSION_IS_CLOSED__DEPRECATED = 62
  SE_SESSION_GET_ATR__DEPRECATED = 63
  SE_SESSION_OPEN_CHANNEL__DEPRECATED = 64
  SE_SESSION_CLOSE__DEPRECATED = 65
  SE_CHANNEL_SELECT_NEXT__DEPRECATED = 66
  SE_CHANNEL_GET_SELECT_RESP__DEPRECATED = 67
  SE_CHANNEL_TRANSMIT__DEPRECATED = 68
  SE_CHANNEL_CLOSE__DEPRECATED = 69
  # End of deprecated Secure Element API syscalls
  CACHE_OPERATION = 70


class OpteeTaCall(enum.IntEnum):
  OPEN_SESSION = 0
  CLOSE_SESSION = 1
  INVOKE_COMMAND = 2
